### PR TITLE
Add dashboards

### PR DESCRIPTION
**Pull request by mnlipp**

### CODE REVIEW

**Comment by mnlipp** [comment]
Of course, your original dashboard should go to `grafana-dashbords` as well and `Readme.md` needs to be updated.

**Comment by mulbc** [comment]
FYI - a container build is available here:
https://quay.io/repository/mulbc/fritzdocsis

It uses the existing Dockerfile in the repo.

I can see that a kubernetes manifest might make deploying this easier, if you want we can add that by itself.

Also: Please explain what's different/better about your Dashboard

**Comment by mnlipp** [comment]
> FYI - a container build is available here: https://quay.io/repository/mulbc/fritzdocsis

Is this mentioned somewhere? Seeing the Dockerfile, I assumed that it should be but failed to find a URL mentioned in the Readme or elsewhere.

> It uses the existing Dockerfile in the repo.

I wonder how it worked without the libc6-compat, but I suppose you used another system for building and thus git a differently linked binary.

> 
> I can see that a kubernetes manifest might make deploying this easier, if you want we can add that by itself.

The PR is just a "proposal". I'd find it useful, but do as you like.

> Also: Please explain what's different/better about your Dashboard

It's not intended as a replacement, rather as an alternative. It's a bit prettier though because it has units at the y-axes. The MSE filters by DOCSIS version and thus avoids the 0 dB line for the 3.1 channel (with everything really used in the -30ies). The legend uses the frequency not the channel number which isn't very informative. I've arranged the panels by "importance" from my experience when the connection was very bad. The top panels are those that I look at regularly.

But most things are a matter of taste. So, repeating myself, its intended as an alternative for starting your own customized version (which you usually do anyway).

**Comment by mulbc** [comment]
I cherry-picked your dashboard since this PR contains two commits - the dashboard and the kubernetes changes

**Pull request closed without merging**
